# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Biolab' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'


  # Pods for Biolab

  target 'Biolab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  end

  target 'BiolabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
